name: Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # ref. https://github.com/AkhileshNS/heroku-deploy/issues/188
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@1b080913896a5d6d44a18e9e208f8eb1fee9b0f7 # v3.15.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "eml-analyzer"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
